### ISSUE TITLE
decouple `WebTransport` functionality from Yew

### ISSUE THREAD

**Issue by databasedav** [security-union/yew-webtransport#10]
enables using this library with other rust wasm frontend frameworks

**Comment by darioalessandro** [comment]
Hey @databasedav you can use wasm directly for this: https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/src/features/gen_WebTransport.rs would that work for you? which kind of abstraction are you looking for?

**Comment by databasedav** [comment]
@darioalessandro at a high level, it would certainly include removing the yew dependency, which it looks like is being used for channels and callbacks, could we replace these with the oneshot channel in `futures` (which is already a dependency) and `impl Fn`? this would then make https://github.com/security-union/yew-webtransport/issues/11 easier

**Comment by darioalessandro** [comment]
I do not know what that serves, at that point I recommend using the wasm-bindgen directly?

**Comment by darioalessandro** [comment]
I would like you to share more specifics
