### ISSUE TITLE
implement `futures` `Sink`/`Stream`/`AsyncRead`/`AsyncWrite` semantics for webtransport datagrams

### ISSUE THREAD

**Issue by databasedav** [security-union/yew-webtransport#11]
use the abstractions in `futures` to be able to transparently send and receive streams of bytes using webtransport datagrams under the hood

for example, [ws_stream_wasm](https://github.com/najamelan/ws_stream_wasm) does this for websockets

**Comment by darioalessandro** [comment]
nice!! are you planning on taking on this task?

**Comment by databasedav** [comment]
someday :sweat_smile:

**Comment by darioalessandro** [comment]
nah screw it
